# Generated by Django 6.0.3 on 2026-03-23 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=20)),
                ('internal_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('is_static', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_static', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('staff_type', models.CharField(choices=[('teaching', 'Teaching'), ('non_teaching', 'Non Teaching')], default='teaching', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyCustomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faculty')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appfield')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('admission_year', models.IntegerField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('physically_challenged', models.BooleanField(default=False)),
                ('aadhaar', models.CharField(blank=True, max_length=20, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('tenth_year', models.IntegerField(blank=True, null=True)),
                ('tenth_percentage', models.FloatField(blank=True, null=True)),
                ('twelfth_year', models.IntegerField(blank=True, null=True)),
                ('twelfth_percentage', models.FloatField(blank=True, null=True)),
                ('course', models.CharField(blank=True, choices=[('UG', 'UG'), ('PG', 'PG'), ('Research', 'Research')], default='UG', max_length=20, null=True)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('hosteller', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCustomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appfield')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='student_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documenttype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.student')),
            ],
            options={
                'unique_together': {('student', 'document_type')},
            },
        ),
    ]
