# Generated by Django 6.0.3 on 2026-03-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='status',
            field=models.CharField(choices=[('Locked', 'Locked'), ('Requested', 'Requested'), ('Unlocked', 'Unlocked')], default='Locked', max_length=20),
        ),
    ]
